
# Dont print a new line at the start if prompt
add_newline = false

[character]      # The name of the module we are configuring is "character"
success_symbol = "[ξ](bold green)"
error_symbol = "✗"


[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = false
