require("settings.theme")
require("settings.treesitter")
require("settings.lualine")
-- require("settings.luasnip")
require("settings.vsnip")
require("settings.lspstatus")
-- require("settings.statusline")
require("settings.telescope")
require("settings.ident")
require("settings.cmp")
require("settings.lspconfig")
require("settings.outline")
require("settings.colors")
require("settings.trouble")
require("settings.autopairs")


require('nvim-ts-autotag').setup()
